### ISSUE TITLE
Updating sweetCat data

### ISSUE THREAD

**Issue by sousasag** [sczesla/PyAstronomy#11]
Hi,

There was a recent update to the SWEETCat. When I used:
sc.downloadData()
for some reason the data was not locally updated.
When I did:
scs.dataAge() -> close to 0... 

but the number of rows in the data was still outdated.

To solve this, I just removed the local files, and then I had the new data available. But this is just a work around...

Cheers,
Sérgio

**Comment by sczesla** [comment]
Hi,

I checked the download on my machine and it seems to work. My suspicion is that the
data were, indeed, successfully updated (on the disk) following your
call to "sc.downloadData()". However,
they were not immediately re-read, when the download was triggered. This only
happened, when a new class instance was created. 

This comes, of course, a little unexpected and is a flaw in the flow logic.
It should be fixed now.

Cheers,
Stefan
