### ISSUE TITLE
pyasl.ExoplanetEU() - Not really an issue, more a request

### ISSUE THREAD

**Issue by sousasag** [sczesla/PyAstronomy#13]
Hi,

I notice that there is only a good selection of columns for the exoplanet.eu.
Is it difficult to add some extra important columns that are currently missing?

Right now I would like to have the "Radius meas. Method". With this column I can check if a planet detected by Radial Velocity is also transiting the star.

Cheers

**Comment by DanielAndreasen** [comment]
Hi Sérgio,

It is indeed straight forward. In the source code [lline 164](https://github.com/sczesla/PyAstronomy/blob/master/src/pyasl/resBased/exoplanetEU.py#L164) you can just add more columns. You can also do it yourself and create a pull request ;)

Cheers,
Daniel

**Comment by DanielAndreasen** [comment]
Instead of adding just a few more, we could add a `full` parameter which is default set to `False`. When `True` it will present the full table from ExoplanetEU/org.
What do you think Stefan?

By the way, Sérgio have said to me that he might make a pull request on this.

**Comment by sczesla** [comment]
Hi,

it is, indeed, relatively simple. I pushed a commit, which adds the column (dubbed
radius_detection_type in the cvs file containing the database). That is of course only a
quick fix, and I agree with Daniel that a full
coverage of the columns would be more desirable.

As the individual databases are quite heterogeneous, there is not yet an equally satisfying selection
of columns. In fact, the classes are all "stand alone". I have been thinking about "unifying" the
access (including full column coverage) for a longer time (but, obviously, I have not implemented
it yet). However, I believe that would be very useful.

Cheers,
Stefan

**Comment by jason-neal** [comment]
@sousasag  Is this now resolved with ExoplanetEU2,  where all columns are provided?

**Comment by sczesla** [comment]
Closing for now. Please re-open if needed
