### ISSUE TITLE
Put PyAstronomy on pypi

### ISSUE THREAD

**Issue by rdenadai** [sczesla/PyAstronomy#3]
May i suggest putting this library on pypi repository?
And perhaps join the Affiliated Packages on Astropy => http://www.astropy.org/affiliated/index.html

Good job on this!!!
Cheers!

**Comment by leliel12** [comment]
i cant do this

**Comment by sczesla** [comment]
Hi. I know it has been a while. I finally managed to put PyAstronomy on PyPi.
Hope it works!
Cheers, Stefan
