### ISSUE TITLE
version information

### ISSUE THREAD

**Issue by richardgmcmahon** [sczesla/PyAstronomy#34]
Hi, which version is on GitHub is it Version 0.12.0? 

ie. the version documented here: 

http://www.hs.uni-hamburg.de/DE/Ins/Per/Czesla/PyA/PyA/index.html

OK, I can see  it is 

`>>> print(PyAstronomy.__version__)
`

0.13.0beta

**Comment by sczesla** [comment]
Hi,

great you found out. Individual, older version may also be found under "Releases" on github.

Stefan
