### ISSUE TITLE
Acknowledgement

### ISSUE THREAD

**Issue by DanielAndreasen** [sczesla/PyAstronomy#4]
Hi,

I have used your function for doppler shifting a spectra in one of my programs. Because of some computer problems, I needed to remove the dependency from PyAstronomy. So I copy-paste all the code to my own program, and everything is working perfectly.

However, since I didn't do the writing of that function, I would like to acknowledge you for your work.
Is there an official way of doing this or should I just put a link to your webpage in a comment above the function (or anything else you prefer)?

Thanks for your software. It is fantastic!
Cheers,
Daniel

**Comment by sczesla** [comment]
Hi Daniel,

great to hear that it helped you! There is not yet a publication, which one could cite, but
I would be glad if you would simply mention PyA in your acknowledgements and give a link somewhere. (Very) Recently, I added a brief note to the docs:

https://pyastronomy.readthedocs.org/en/latest/pyaCDoc/acknowledgement.html

Cheers,
Stefan

**Comment by DanielAndreasen** [comment]
I will make sure to do that. Thanks for the reply Stefan.
