### ISSUE TITLE
pip friendly "with-ext"

### ISSUE THREAD

**Issue by nonZero** [sczesla/PyAstronomy#40]
Using `python setup.py --with-ext install` is not pip friendly.

A better solution would be extracting a `pyastronomy-occult` package from PyAstronomy.  (Bonus: This package could be distributed in [binary wheels](https://github.com/joerick/cibuildwheel) as well).

Instead of `--with-ext`,  it would be specified as an [extra dependency](https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras) to PyAstronomy:

    pip install pyastronomy[occult]

**Comment by sczesla** [comment]
Thanks. Appears to be a better approach for sure. I will have to look into this solution

**Comment by sczesla** [comment]
Implemented this solution. Hope it works!
