### ISSUE TITLE
Time Series Folding Reference Point

### ISSUE THREAD

**Issue by JackActon** [sczesla/PyAstronomy#44]
The FoldAt command;

PyAstronomy.pyasl.foldAt(time, period, T0=0.0, getEpoch=False)

Takes the input T0, described in the documents as a reference point. I'm folding some time series data of my own, with a known period and epoch. Is there any way of knowing what this reference should be?

Thanks.

**Comment by sczesla** [comment]
Hi,

as far as I understand your description, T0 corresponds to what you call "epoch". That point would be mapped to phase zero.

Cheers

**Comment by sczesla** [comment]
Yes. And all points given by T0+n*period with integer n likewise. I updated and extended the docu, which should no hopefully be clearer.
