### ISSUE TITLE
Generalized ESD

### ISSUE THREAD

**Issue by jcdang** [sczesla/PyAstronomy#45]
If you want to match NIST's R [implementation](https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h3.r),

https://github.com/sczesla/PyAstronomy/blob/595f1eaf32f99493931d72404f7e0877e88ca9e3/src/pyasl/asl/outlier.py#L62

should be
```python
    xstd = xm.std(ddof=1) 
```

**Comment by sczesla** [comment]
Thanks. That is true. I added an option to enable consistent behavior. I did not want to change existing default behavior, which is not wrong either as far as I can tell. Stefan
