### ISSUE TITLE
NavigationToolbar2TkAg deprecated

### ISSUE THREAD

**Issue by MingjieJian** [sczesla/PyAstronomy#46]
Hi Stefan, 

I was using the pyaGui.ContinuumInteractive to do some normalization and it worked well, but recently after I upgraded matplotlib I found the package matplotlib.backends.backend_tkagg.NavigationToolbar2TkAgg is deprecated and an error appear when I tried to import pyaGui. I did a brief search and found someone said that for now NavigationToolbar2Tk should be used. It will be great if I can use pyaGui with the newest matplotlib.
(https://stackoverflow.com/questions/50330320/what-to-use-instead-of-navigationtoolbar2tkagg)

Thanks.

**Comment by sczesla** [comment]
Hi,
Thanks for reporting. This is an annoying issue, which should be solved in the current development branch (master). Running a test, I encountered another issue related to an apparent API change concerning show/draw in canvas. I will draft a new release soon to distribute the changes sooner.
Cheers, Stefan
