### ISSUE TITLE
GeneralizedESD gone 

### ISSUE THREAD

**Issue by EtienneGagnon1** [sczesla/PyAstronomy#47]
The generalized ESD function that appears in the documentation seems to be gone from the package. Would it be possible to restore it? 

https://pyastronomy.readthedocs.io/en/latest/pyaslDoc/aslDoc/outlier.html?highlight=generalizedESD#outlier-detection

**Comment by sczesla** [comment]
Hi, this was not supposed to happen. I can run the example with a fresh install of version 0.15.0 from PYPI. What is the error message and which version of python are you running?

**Comment by EtienneGagnon1** [comment]
Nevermind it's actually fine but the documentation should be updated since it is no longer located at 
``PyAstronomy.pyasl.generalizedESD`` 
bur rather at 
``PyAstronomy.pyasl.asl.outlier.generalizedESD``

**Comment by sczesla** [comment]
OK. Very good that it is not gone. I am still a bit confused because for me

`from PyAstronomy import pyasl`
`dir(pyasl)`

does show the presence of generalizedESD. It is part of outlier, so that works as well as you show. Not sure how this behavior is produced

**Comment by EtienneGagnon1** [comment]
> OK. Very good that it is not gone. I am still a bit confused because for me
> 
> `from PyAstronomy import pyasl`
> `dir(pyasl)`
> 
> does show the presence of generalizedESD. It is part of outlier, so that works as well as you show. Not sure how this behavior is produced

This actually also works for me but my IDE was showing the import as producing an error.  It seems like the problem is on my end so please ignore this issue. Sorry for taking your time.
