### ISSUE TITLE
atomic symbol of atom 112~118

### ISSUE THREAD

**Issue by yqcaogit** [sczesla/PyAstronomy#58]
The atomic symbols of atom 112~118 are different from [Wikipedia](https://en.wikipedia.org/wiki/Periodic_table) and the PubChem: [https://pubchem.ncbi.nlm.nih.gov/periodic-table/](url)

**Comment by sczesla** [comment]
Thanks for pointing this out. It appears my source was a bit outdated and still had placeholder names for those. I pushed a commit to fix this. Stefan
